### ISSUE TITLE
Move to core or purescript-eff

### ISSUE THREAD

**Issue by natefaubion** [hdgarrood/purescript-eff-functions#3]
/cc @paf31 @garyb 

It would be great to see this in core or purescript-eff. I'd like to add some additional magic-do rules to support something like https://github.com/slamdata/purescript-halogen-vdom/pull/15.

**Comment by hdgarrood** [comment]
No objections from me on this :smile: I don't have a particular preference either way re core or eff.

**Comment by nwolverson** [comment]
Definitely seems a good complement to the current optimisation rules around `FnX`

**Comment by garyb** [comment]
If we are going to add some compiler magic for them, then I guess core would be the better place :)

**Comment by hdgarrood** [comment]
Good point. How do we feel about compiler magic? The only disadvantage I can think of is that it's just one more thing that has the potential to go wrong in a slightly confusing and weird way but that doesn't seem too much of a risk, and it seems worth it for the perf boost.

Now that we have an imperative core stage, might it be feasible to define these sorts of optimisations in libraries, incidentally?

**Comment by garyb** [comment]
> Now that we have an imperative core stage, might it be feasible to define these sorts of optimisations in libraries, incidentally?

That was the eventual hope for all kinds of inlining/rewriting rules yeah. I still like the idea very much!

**Comment by hdgarrood** [comment]
Great. Having a (relatively) clear path for later 'unmagickifying' this if we do add compiler magic makes this much more attractive as an option IMO.

**Comment by hdgarrood** [comment]
(I mean, that's where I was coming from in my previous comment, in case that wasn't clear.)

**Comment by paf31** [comment]
@hdgarrood Would you still like to move this into core, or do you think it'd be better to create a new module in `eff`?

**Comment by hdgarrood** [comment]
I reckon it might make the most sense to create a new module in `eff`, since IIRC this code doesn't depend on any libraries other than `eff`.

**Comment by garyb** [comment]
That sounds good to me too, I hadn't thought of that before.

**Comment by hdgarrood** [comment]
`eff` itself is in core already anyway, right?

**Comment by garyb** [comment]
Yeah, exactly :)

**Comment by hdgarrood** [comment]
Ok cool, just checking :)

**Comment by paf31** [comment]
https://github.com/purescript/purescript-eff/pull/18

**Comment by hdgarrood** [comment]
I'd also appreciate a PR replacing the code with a deprecation notice and linking to `eff` :) I'd do it myself but I won't have access to my machine until tomorrow (by which time I will probably have forgotten).
